/*
 * generated by Xtext 2.9.1
 */
package com.communote.restws.validation

import org.eclipse.xtext.validation.Check
import com.communote.restws.restWebservice.AbstractParameterAttribute
import com.communote.restws.restWebservice.RestWebservicePackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class RestWebserviceValidator extends AbstractRestWebserviceValidator {
	
    @Check
    def checkReservedAttributeNames(AbstractParameterAttribute paramAttribute) {
        if (paramAttribute.getName().equals("_method")) {
            error("Attributes and parameter with the name '_method' are not allowed, "
                    + "because of the tunneling of the HTTP methods PUT and DELETE",
                    RestWebservicePackage.Literals.ABSTRACT_PARAMETER_ATTRIBUTE__NAME);
        }
    }

    // TODO convert the other checks from RestWebserviceChecks.chk to @Check methods
	
}
