/*
 * generated by Xtext 2.9.1
 */
package com.communote.restws


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RestWebserviceRuntimeModule extends AbstractRestWebserviceRuntimeModule {
}
