/*
 * generated by Xtext 2.9.1
 */
package com.communote.restws


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RestWebserviceStandaloneSetup extends RestWebserviceStandaloneSetupGenerated {

	def static void doSetup() {
		new RestWebserviceStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
